[tool.poetry]
name = "homework-14-1-classes"
version = "0.1.0"
description = ""
authors = ["Artem <artemiy9999@gmail.com>"]
readme = "README.md"

packages = [
    { include = "homework" }
]

[tool.poetry.dependencies]
python = "^3.12"


[tool.poetry.group.dev.dependencies]
pytest = "^9.0.1"
pytest-cov = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
